global:
  tlsDisable: false

server:
  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/vault-server-tls/ca.crt
  standalone:
    config: |-
      ui = true
      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/vault/userconfig/vault-server-tls/tls.crt"
        tls_key_file  = "/vault/userconfig/vault-server-tls/tls.key"
        tls_client_ca_file = "/vault/userconfig/vault-server-tls/ca.crt"
      }
      storage "file" {
        path = "/vault/data"
      }
  volumes:
    - name: userconfig-vault-server-tls
      secret:
        defaultMode: 420
        secretName: hashicorp-vault-server-tls
  volumeMounts:
    - mountPath: /vault/userconfig/vault-server-tls
      name: userconfig-vault-server-tls
      readOnly: true

ui:
  enabled: true
  annotations:
    "lbipam.cilium.io/ips": ${ip_address}
  serviceType: "LoadBalancer"
  # ingress:
  #   enabled: true
  #   activeService: false
  #   annoations:
  #     cert-manager.io/cluster-issuer: cloudflare-letsencrypt-${environment}
  #     ingress.cilium.io/loadbalancer-mode: shared
  #   hosts:
  #     - host: ${hashicorp_vault_domain}
  #   ingressClassName: cilium
  #   tls:
  #     - secretName: hashicorp-vault-tls
  #       hosts:
  #         - ${hashicorp_vault_domain}
