controller:
  # loadBalancerIP: 172.16.4.30
  loadBalancerIP: 172.28.155.30

  config:
    hsts: true
    hsts-include-subdomains: true
    hsts-max-age: "31536000"

  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
